apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v2
  namespace: demo
  labels:
    app: demo-app-v2
    environment: development
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-v2
  template:
    metadata:
      labels:
        app: demo-app-v2
        environment: development
        version: v2
    spec:
      initContainers:
      - name: setup
        image: node:18-alpine
        command: ["/bin/sh"]
        args: ["-c", "cp -r /app-source/* /app/ && cd /app && npm install --production"]
        volumeMounts:
        - name: app-source
          mountPath: /app-source
        - name: app-workdir
          mountPath: /app
      containers:
      - name: demo-app
        image: node:18-alpine
        command: ["/bin/sh"]
        args: ["-c", "cd /app && npm start"]
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-workdir
          mountPath: /app
      volumes:
      - name: app-source
        configMap:
          name: demo-app-source
      - name: app-workdir
        emptyDir: {}
