apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
  annotations:
    change.company.com/id: "CHG-2025-001"
  labels:
    app: demo-app
    environment: development
    team: demo-team
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
