apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: change-validation-webhook
spec:
  webhooks:
  - name: change-validation.company.com
    clientConfig:
      service:
        name: admission-controller
        namespace: admission-controller
        path: "/admit"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyVENDQXBXZ0F3SUJBZ0lVRExpTExSSDNLSnlvUm0vZlJLdE1Jb0VYVWg0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SWXdGQVlEVlFRSERBMVRZVzRnUm5KaApibU5wYzJOdk1SQXdEZ1lEVlFRS0RBZERiMjF3WVc1NU1TQXdIZ1lEVlFRRERCZEJaRzFwYzNOcGIyNGdRMjl1CmRISnZiR3hsY2lCRFFUQWVGdzB5TlRBMk1UTXhORFEyTWpKYUZ3MHlOakEyTVRNeE5EUTJNakphTUdZeEN6QUoKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFUQpNQTRHQTFVRUNnd0hRMjl0Y0dGdWVURWdNQjRHQTFVRUF3d1hRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnClEwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ1piSjc1S2Fid0NrekdVd0UKZnJlbzl1cW9sak40UUc1Q0FpZDNJNE9kZy91QW1CWjlaNzFvOEdxZnU5d09OeFFZQWFkSjBTMmFkM3JLVzVkSQp4VWNQZzZwQ2xpVUl4aU4xYWVkbFdZRmNUbXNpL1BuVDk4dUdFTlZXQ0JDQWxmSkREOExBOUMwM1ZydHFUWWZVCmExTDQyZkZlTU0wYVA5S0d2NkpxejUrU0M3aHJKNUhhdWUwL2tWZ2Zna042QWE3OEM5Y0dvUzRCbTZ5RjBRNHQKNmdCMmhDdXM4QU90Z3Y4MmY2ZGZiRjR3bXN4NDMzUTZ2UzhwVk15VmRiVTVzUk03bXRGWWtVcFhhUmZMV3U4NAo3NWkzVUw3M3lkcjZtbFZVZ2lTbDRaOGI3aUQxN2prM1MvZmFxczR2elNiRTREaW1FdmszUSsyRi9yem54NmZhCk9rTzdBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlNnU0tKSytwK0pqWXhtWUZXTDRHVVVZUlZXNVRBZkJnTlYKSFNNRUdEQVdnQlNnU0tKSytwK0pqWXhtWUZXTDRHVVVZUlZXNVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3drN3hCREZDR2FFQmYyWmFqQ3JDSmZmOUl5OTQvR21YMkZtTmY4ekZECndoK3dMYURSbmJmMTlkTUVCRHZkeWtMT3ZuQmdaRDB4Z0pwTEU1Sk02a1pqUWdkbFplYnFQL1d5Y09aQ2oreFkKOXN2RFMwSk5GODk5R2o4SC9wYnJwbFVURmFib0dDS3MzeGdnZ0ZOWHQ3RUx5OERZM3ZxL08vdDBhdHJkcXZySgpIcU9TckpyTTdtOWM5a1VRbXFCTDB2Rm03a2lmVVcrdWVZeDlncVFnWlBOeDUxbndRSk4wWlkwQ1FVMzVVRzR6CjljMUFQNy9NNkV5S24vRVVBS2VhYVh1YVRwSmRONjFrbm9TK2YrWUJsWitVTzlKSnMvcFEyeHBnWm5oMm83ZDUKY0hzR2hsMGFBK2N6OVdYZUlxWHZ6MExTcGRoZ2FLdVNLcFRGMDZoZXplYlIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments"]
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"] 
      resources: ["services", "configmaps"]
    namespaceSelector:
      matchLabels:
        change-validation: "enabled"
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
