apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: change-validation-webhook
spec:
  clientConfig:
    service:
      name: admission-controller
      namespace: admission-controller
      path: "/admit"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"] 
    resources: ["services", "configmaps"]
  namespaceSelector:
    matchLabels:
      change-validation: "enabled"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
